/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.25.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * statuses of a member in a group
 */
export type MemberGroupStatus = 'VALID' | 'EXPIRED';

export const MemberGroupStatus = {
    VALID: 'VALID' as MemberGroupStatus,
    EXPIRED: 'EXPIRED' as MemberGroupStatus
};

