/**
 * Perun RPC API
 * Perun Remote Procedure Calls Application Programming Interface
 *
 * The version of the OpenAPI document: 3.25.0
 * Contact: perun@cesnet.cz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SponsoredUserData { 
    guestName?: string;
    firstName?: string;
    lastName?: string;
    titleBefore?: string;
    titleAfter?: string;
    namespace?: string;
    email?: string;
    password?: string;
    login?: string;
}

